version: '3.8'

services:
  mf_drawer:
    build: ./mf_drawer
    volumes:
      - ./mf_drawer/src:/app/src
      - ./mf_drawer/public:/app/public
    ports:
      - "3000:3000"

  mf_videos:
    build: ./mf_videos
    volumes:
      - ./mf_videos/src:/app/src
      - ./mf_videos/public:/app/public
    ports:
      - "3002:3000"

  bff:
    build: ./bff
    volumes:
      - ./bff/src:/app/src
    ports:
      - "3001:3001"

